issue/3163 Added correctToPass and _isItemScoring support
adaptlearning/adapt-contrib-assessment pull request #132
Opened 2021-06-14 09:06 UTC by oliverfoster

https://github.com/adaptlearning/adapt_framework/issues/3163

### Added
* Added `correctToPass` to compliment `scoreToPass`

### Changed
* Use `QuestionModel.score`. `QuestionModel.maxScore` and `QuestionModel.minScore` rather than `_questionWeight` and `_isCorrect`

2021-06-14 10:37 UTC, cahirodoherty-learningpool approved these changes
👀

2021-06-14 16:35 UTC, eleanor-heath commented on js/adapt-assessmentArticleModel.js
> +      const isPass = isPercentageBased ? (scoreAsPercent >= scoreToPass && correctAsPercent >= correctToPass) : (score >= scoreToPass && correctCount >= correctToPass);
Can we format this ternary statement a bit better and separate it out onto different lines like how you have formatted this one

```
const isPass = !isComplete
? false
: (assessmentsConfig._isPercentageBased !== false)
  ? scoreAsPercent >= scoreToPass && correctAsPercent >= correctToPass
  : score >= scoreToPass && correctCount >= correctToPass;
```

2021-06-14 16:35 UTC, eleanor-heath approved these changes

2021-06-23 09:37 UTC, tomgreenfield commented on properties.schema
> +                  "title": "Correct mark",
```suggestion
                  "title": "Correct pass mark",
```

2021-06-23 09:37 UTC, tomgreenfield commented on properties.schema
> +                  "help": "The minimum number of correct questions required by the learner to pass the assessment.",
Should this mention that this is/could be a percentage?

2021-06-23 09:37 UTC, tomgreenfield commented on properties.schema
> +                  "title": "Correct mark",
```suggestion
                  "title": "Correct pass mark",
```

2021-06-23 09:37 UTC, tomgreenfield commented on js/assessment.js
>          scoreToPass: assessmentsConfig._scoreToPass,
`scoreToPass` and `isPercentageBased` are already available in variables above.

Should `correctToPass` also be surfaced in the state?

2021-06-23 09:37 UTC, tomgreenfield commented on js/adapt-assessmentArticleModel.js
>        this.set('_questions', questions);
Can be included in the `set()` starting on line 749.

2021-06-24 10:04 UTC, tomgreenfield requested changes

2021-06-24 10:04 UTC, tomgreenfield commented on README.md
> +>**\_isPercentageBased** (boolean): Determines whether the values of **\_scoreToPass** and **\_correctToPass** should be treated as a percentage or as the raw score and correctness. For example, if *
```suggestion
>**\_isPercentageBased** (boolean): Determines whether the values of **\_scoreToPass** and **\_correctToPass** should be treated as percentages or as the raw score and correctness. For example, if **\_isPercentageBased** is set to `true`, a **\_scoreToPass** value of `60` will be treated as `60%`.  
```

2021-06-24 10:04 UTC, tomgreenfield commented on README.md
> +>**\_isPercentageBased** (boolean): Determines whether the valuex of **\_scoreToPass** and **\_correctToPass** should be treated as a percentage or as the raw score and correctness. For example, if *
```suggestion
>**\_isPercentageBased** (boolean): Determines whether the values of **\_scoreToPass** and **\_correctToPass** should be treated as percentages or as the raw score and correctness. For example, if **\_isPercentageBased** is set to `true`, a **\_scoreToPass** value of `60` will be treated as `60%`.   
```

2021-06-24 10:04 UTC, tomgreenfield commented on properties.schema
> +                  "help": "Determines whether the values of the 'Pass mark' should be treated as a percentage (default) or as the raw score and correctness.",
```suggestion
                  "help": "Determines whether the pass mark values should be treated as percentages (default) or as the raw score and correctness.",
```

2021-06-29 08:41 UTC, tomgreenfield approved these changes
:eye:

2021-07-01 11:53 UTC, merged